--[[

│تم تطوير وبرمجة السورس من قبل جاك ✾ .
│@ V_P_E
#-------------------------------------------------------------------
]]

local function bassela(msg,MsgText)
if msg.type ~= "pv" then
if MsgText[1] == "زخرفه" then
redis:setex(black..":basselNow:"..msg.sender_user_id_,500,true)
sendMsg(msg.chat_id_,msg.id_,"| حسننا , الان يمكنك ارسال الاسم ولبعض الرموز المميزه اكتب رموز")    
return false
end

if redis:get(black..":basselNow:"..msg.sender_user_id_) then
redis:del(black..":basselNow:"..msg.sender_user_id_)
if utf8.len(msg.text) > 300 then
sendMsg(msg.chat_id_,msg.id_,"| لا يمكنك زخرفه اكثر من 20 حرف \n| ارسل امر زخرفه وحاول مجددا بحروف اقل")    
return false
elseif msg.text:match("\n") then
sendMsg(msg.chat_id_,msg.id_,"| لا يمكن زخرفه نص يحتوي على اكثر من سطر .")
return false
end
local EmojeS = {
' 𓁻',
' 𓏴  ',
' 𓏶 ',
' 𓏡',
' 𓏢', 
' 𓏣', 
' ☽‘',
' 𖠱²²', 
'▽', 
' 𖡛“', 
' 𖡚℡', 
' 𖡨', 
}

local Emoje = {
' ♕',
' 𖤍',
'˛𖤓',
' ཻ ☫',
' ♫ ',
' 𖠶 ',
' 𖠲',
' 𖡥',
'  ☬',
' 𖤐',
' 𓇼',
' ♘  '
}


local bassel = Text:gsub('ض','ضِٰـِۢ')
bassel = bassel:gsub('ص','صِٰـِۢ')
bassel = bassel:gsub('ث','ثِٰـِۢ')
bassel = bassel:gsub('ق','قِٰـِۢ')
bassel = bassel:gsub('ف','فِٰ͒ـِۢ')
bassel = bassel:gsub('غ','غِٰـِۢ')
bassel = bassel:gsub('ع','عِٰـِۢ')
bassel = bassel:gsub('خ','خِٰ̐ـِۢ')
bassel = bassel:gsub('ح','حِٰـِۢ')
bassel = bassel:gsub('ج','جِٰـِۢ')
bassel = bassel:gsub('ش','شِٰـِۢ')
bassel = bassel:gsub('س','سِٰـِۢ')
bassel = bassel:gsub('ي','يِٰـِۢ')
bassel = bassel:gsub('ب','بِٰـِۢ')
bassel = bassel:gsub('ل','لِٰـِۢ')
bassel = bassel:gsub('ا','آ')
bassel = bassel:gsub('ت','تِٰـِۢ')
bassel = bassel:gsub('ن','نِٰـِۢ')
bassel = bassel:gsub('م','مِٰـِۢ')
bassel = bassel:gsub('ك','ڪِٰـِۢ')
bassel = bassel:gsub('ط','طِٰـِۢ')
bassel = bassel:gsub('ظ','ظِٰـِۢ')
bassel = bassel:gsub('ء','ء')
bassel = bassel:gsub('ؤ','ؤ')
bassel = bassel:gsub('ر','ر')
bassel = bassel:gsub('ى','ى')
bassel = bassel:gsub('ز','ز')
bassel = bassel:gsub('و','ﯛ̲୭')
bassel = bassel:gsub('ه','ۿۿہ')
bassel = bassel:gsub('a','𝗮')
bassel = bassel:gsub('A','𝗔')
bassel = bassel:gsub("b","𝗯")
bassel = bassel:gsub("B","𝗕")
bassel = bassel:gsub("c","𝗰")
bassel = bassel:gsub("C","𝗖")
bassel = bassel:gsub("d","𝗱")
bassel = bassel:gsub("D","𝗗")
bassel = bassel:gsub("e","𝗲")
bassel = bassel:gsub("E","𝗘")
bassel = bassel:gsub("f","𝗳")
bassel = bassel:gsub("F","𝗙")
bassel = bassel:gsub("g","𝗴")
bassel = bassel:gsub("G","𝗚")
bassel = bassel:gsub("h","𝗵")
bassel = bassel:gsub("H","𝗛")
bassel = bassel:gsub("i","𝗹")
bassel = bassel:gsub("I","𝗜")
bassel = bassel:gsub("j","𝗝")
bassel = bassel:gsub("J","𝗝")
bassel = bassel:gsub("k","𝗸")
bassel = bassel:gsub("K","𝗞")
bassel = bassel:gsub("l","𝗹")
bassel = bassel:gsub("L","𝗟")
bassel = bassel:gsub("m","𝗺")
bassel = bassel:gsub("M","𝗠")
bassel = bassel:gsub("n","𝗻")
bassel = bassel:gsub("N","𝗡")
bassel = bassel:gsub("o","𝗼")
bassel = bassel:gsub("O","𝗢")
bassel = bassel:gsub("p","𝗽")
bassel = bassel:gsub("P","𝗣")
bassel = bassel:gsub("q","𝗾")
bassel = bassel:gsub("Q","𝗤")
bassel = bassel:gsub("r","𝗿")
bassel = bassel:gsub("R","𝗥")
bassel = bassel:gsub("s","𝘀")
bassel = bassel:gsub("S","𝗦")
bassel = bassel:gsub("t","𝘁")
bassel = bassel:gsub("T","𝗧")
bassel = bassel:gsub("u","𝘂")
bassel = bassel:gsub("U","𝗨")
bassel = bassel:gsub("v","𝘃")
bassel = bassel:gsub("V","𝗩")
bassel = bassel:gsub("w","𝘄")
bassel = bassel:gsub("W","𝗪")
bassel = bassel:gsub("x","𝘅")
bassel = bassel:gsub("X","𝗫")
bassel = bassel:gsub("y","𝘆")
bassel = bassel:gsub("Y","𝗬")
bassel = bassel:gsub("z","𝘇")
bassel = bassel:gsub("Z","𝗭")



local bassel2 = Text:gsub('ض','ضَٰـُـٰٓ')
bassel2 = bassel2:gsub('ص','صَٰـُـٰٓ')
bassel2 = bassel2:gsub('ث','ثَٰـُـٰٓ')
bassel2 = bassel2:gsub('ق','قَٰـُـٰٓ')
bassel2 = bassel2:gsub('ف','فَٰ͒ـُـٰٓ')
bassel2 = bassel2:gsub('غ','غَٰـُـٰٓ')
bassel2 = bassel2:gsub('ع','عَٰـُـٰٓ')
bassel2 = bassel2:gsub('خ','خَٰ̐ـُـٰٓ')
bassel2 = bassel2:gsub('ح','حَٰـُـٰٓ')
bassel2 = bassel2:gsub('ج','جَٰـُـٰٓ')
bassel2 = bassel2:gsub('ش','شَٰـُـٰٓ')
bassel2 = bassel2:gsub('س','سَٰـُـٰٓ')
bassel2 = bassel2:gsub('ي','يَٰـُـٰٓ')
bassel2 = bassel2:gsub('ب','بَٰـُـٰٓ')
bassel2 = bassel2:gsub('ل','لَٰـُـٰٓ')
bassel2 = bassel2:gsub('ا','آ')
bassel2 = bassel2:gsub('ت','تَٰـُـٰٓ')
bassel2 = bassel2:gsub('ن','نَٰـُـٰٓ')
bassel2 = bassel2:gsub('م','مَٰـُـٰٓ')
bassel2 = bassel2:gsub('ك','ڪَٰـُـٰٓ')
bassel2 = bassel2:gsub('ط','طَٰـُـٰٓ')
bassel2 = bassel2:gsub('ظ','ظَٰـُـٰٓ')
bassel2 = bassel2:gsub('ء','ء')
bassel2 = bassel2:gsub('ؤ','ؤ')
bassel2 = bassel2:gsub('ر','ر')
bassel2 = bassel2:gsub('ى','ى')
bassel2 = bassel2:gsub('ز','ز')
bassel2 = bassel2:gsub('و','ﯛ̲୭')
bassel2 = bassel2:gsub("ه", "ۿۿہ")
bassel2 = bassel2:gsub('a',"𝖆")
bassel2 = bassel2:gsub('A',"𝖆")
bassel2 = bassel2:gsub("b","𝖇")
bassel2 = bassel2:gsub("B","𝖇")
bassel2 = bassel2:gsub("c","𝖈")
bassel2 = bassel2:gsub("C","𝖈")
bassel2 = bassel2:gsub("d","𝖉")
bassel2 = bassel2:gsub("D","𝖉")
bassel2 = bassel2:gsub("e","𝖊")
bassel2 = bassel2:gsub("E","𝖊")
bassel2 = bassel2:gsub("f","𝖋")
bassel2 = bassel2:gsub("F","𝖋")
bassel2 = bassel2:gsub("g","𝖌")
bassel2 = bassel2:gsub("G","𝖌")
bassel2 = bassel2:gsub("h","𝖍")
bassel2 = bassel2:gsub("H","𝖍")
bassel2 = bassel2:gsub("i","𝖎")
bassel2 = bassel2:gsub("I","𝖎")
bassel2 = bassel2:gsub("j","𝖏")
bassel2 = bassel2:gsub("J","𝖏")
bassel2 = bassel2:gsub("k","𝖐")
bassel2 = bassel2:gsub("K","𝖐")
bassel2 = bassel2:gsub("l","𝖑")
bassel2 = bassel2:gsub("L","𝖑")
bassel2 = bassel2:gsub("m","𝖒")
bassel2 = bassel2:gsub("M","𝖒")
bassel2 = bassel2:gsub("n","𝖓")
bassel2 = bassel2:gsub("N","𝖓")
bassel2 = bassel2:gsub("o","𝖔")
bassel2 = bassel2:gsub("O","𝖔")
bassel2 = bassel2:gsub("p","𝖕")
bassel2 = bassel2:gsub("P","𝖕")
bassel2 = bassel2:gsub("q","𝖖")
bassel2 = bassel2:gsub("Q","𝖖")
bassel2 = bassel2:gsub("r","𝖗")
bassel2 = bassel2:gsub("R","𝖗")
bassel2 = bassel2:gsub("s","𝖘")
bassel2 = bassel2:gsub("S","𝖘")
bassel2 = bassel2:gsub("t","𝖙")
bassel2 = bassel2:gsub("T","𝖙")
bassel2 = bassel2:gsub("u","𝖚")
bassel2 = bassel2:gsub("U","𝖚")
bassel2 = bassel2:gsub("v","𝖛")
bassel2 = bassel2:gsub("V","𝖛")
bassel2 = bassel2:gsub("w","𝖜")
bassel2 = bassel2:gsub("W","𝖜")
bassel2 = bassel2:gsub("x","𝖝")
bassel2 = bassel2:gsub("X","𝖝")
bassel2 = bassel2:gsub("y","𝖞")
bassel2 = bassel2:gsub("Y","𝖞")
bassel2 = bassel2:gsub("z","𝖟")
bassel2 = bassel2:gsub("Z","𝖟")


local bassel3= Text:gsub('ض','ض')
bassel3= bassel3:gsub('ص','ص')
bassel3= bassel3:gsub('ث','ثہ')
bassel3= bassel3:gsub('ق','ق')
bassel3= bassel3:gsub('ف','فُہ')
bassel3= bassel3:gsub('غ','غہ')
bassel3= bassel3:gsub('ع','عہ')
bassel3= bassel3:gsub('ه','هٰہٰٖ')
bassel3= bassel3:gsub('خ','خہ')
bassel3= bassel3:gsub('ح','حہ')
bassel3= bassel3:gsub('ج','جہ')
bassel3= bassel3:gsub('د','د')
bassel3= bassel3:gsub('ذ','ذ')
bassel3= bassel3:gsub('ش','شہ')
bassel3= bassel3:gsub('س','سہ')
bassel3= bassel3:gsub('ي','يہ')
bassel3= bassel3:gsub('ب','بّ')
bassel3= bassel3:gsub('ل','لہ')
bassel3= bassel3:gsub('ا','ا')
bassel3= bassel3:gsub('ت','تہ')
bassel3= bassel3:gsub('ن','نٰہٰٖ')
bassel3= bassel3:gsub('م','مٰہٰٖ')
bassel3= bassel3:gsub('ك','كُہ')
bassel3= bassel3:gsub('ط','طہ')
bassel3= bassel3:gsub('ئ','ئ ْٰ')
bassel3= bassel3:gsub('ء','ء')
bassel3= bassel3:gsub('ؤ','ؤ')
bassel3= bassel3:gsub('ر','رَ')
bassel3= bassel3:gsub('لا','لہا')
bassel3= bassel3:gsub('ى','ىْ')
bassel3= bassel3:gsub('ة','ة')
bassel3= bassel3:gsub('و','و')
bassel3= bassel3:gsub('ز','ز')
bassel3= bassel3:gsub('ظ','ظۗہٰٰ')
bassel3= bassel3:gsub('q','𝐪')
bassel3= bassel3:gsub('Q','𝐪')
bassel3= bassel3:gsub('w','𝐰')
bassel3= bassel3:gsub('W','𝐰')
bassel3= bassel3:gsub('e','𝐞')
bassel3= bassel3:gsub('E','𝐞')
bassel3= bassel3:gsub('r','𝐫')
bassel3= bassel3:gsub('R','𝐫')
bassel3= bassel3:gsub('t','𝐭')
bassel3= bassel3:gsub('T','𝐭')
bassel3= bassel3:gsub('y','𝐲')
bassel3= bassel3:gsub('Y','𝐲')
bassel3= bassel3:gsub('u','𝐮')
bassel3= bassel3:gsub('i','𝐢')
bassel3= bassel3:gsub('o','𝐨')
bassel3= bassel3:gsub('p','𝐩')
bassel3= bassel3:gsub('a','𝐚')
bassel3= bassel3:gsub('s','𝐬')
bassel3= bassel3:gsub('d','𝐝')
bassel3= bassel3:gsub('f','𝐟')
bassel3= bassel3:gsub('g','𝐠')
bassel3= bassel3:gsub('h','𝐡')
bassel3= bassel3:gsub('j','𝐣')
bassel3= bassel3:gsub('k','𝐤')
bassel3= bassel3:gsub('U','𝐮')
bassel3= bassel3:gsub('I','𝐢')
bassel3= bassel3:gsub('O','𝐨')
bassel3= bassel3:gsub('P','𝐩')
bassel3= bassel3:gsub('A','𝐚')
bassel3= bassel3:gsub('S','𝐬')
bassel3= bassel3:gsub('D','𝐝')
bassel3= bassel3:gsub('F','𝐟')
bassel3= bassel3:gsub('G','𝐠')
bassel3= bassel3:gsub('H','𝐡')
bassel3= bassel3:gsub('J','𝐣')
bassel3= bassel3:gsub('K','𝐤')
bassel3= bassel3:gsub('L','𝐥')
bassel3= bassel3:gsub('l','𝐥')
bassel3= bassel3:gsub('z','𝐳')
bassel3= bassel3:gsub('Z','𝐳')
bassel3= bassel3:gsub('x','𝐱')
bassel3= bassel3:gsub('X','ẋ')
bassel3= bassel3:gsub('c','𝐜')
bassel3= bassel3:gsub('C','𝐜')
bassel3= bassel3:gsub('v','𝐯')
bassel3= bassel3:gsub('V','𝐯')
bassel3= bassel3:gsub('b','𝐛')
bassel3= bassel3:gsub('B','𝐛')
bassel3= bassel3:gsub('n','𝐧')
bassel3= bassel3:gsub('N','𝐧')
bassel3= bassel3:gsub('m','𝐦')
bassel3= bassel3:gsub('M','𝐦')


local bassel4= Text:gsub('ض','ضۜہٰٰ')
bassel4= bassel4:gsub('ص','ضۜہٰٰ')
bassel4= bassel4:gsub('ث','ثہٰٰ')
bassel4= bassel4:gsub('ق','قྀ̲ہٰٰ')
bassel4= bassel4:gsub('ف','ف͒ہٰٰ')
bassel4= bassel4:gsub('غ','غہٰٰ')
bassel4= bassel4:gsub('ع','عہٰٰ')
bassel4= bassel4:gsub('ه','هٰہٰٖ')
bassel4= bassel4:gsub('خ','خٰ̐ہ ')
bassel4= bassel4:gsub('ح','حہٰٰ')
bassel4= bassel4:gsub('ج','جـٰ̲ـہْۧ')
bassel4= bassel4:gsub('د','دٰ')
bassel4= bassel4:gsub('ذ','ذِٰ')
bassel4= bassel4:gsub('ش','شِٰہٰٰ')
bassel4= bassel4:gsub('س','سٰٓ')
bassel4= bassel4:gsub('ي','يِٰہ')
bassel4= bassel4:gsub('ب','بّہ')
bassel4= bassel4:gsub('ل','لـٰ̲ـہ')
bassel4= bassel4:gsub('ا','آ')
bassel4= bassel4:gsub('ت','تَہَٰ')
bassel4= bassel4:gsub('ن','نَِہ')
bassel4= bassel4:gsub('م','مٰ̲ہ')
bassel4= bassel4:gsub('ك','ڪٰྀہٰٰ')
bassel4= bassel4:gsub('ط','طۨہٰٰ')
bassel4= bassel4:gsub('ئ','ئ ْٰ')
bassel4= bassel4:gsub('ء','ء')
bassel4= bassel4:gsub('ؤ','ؤ')
bassel4= bassel4:gsub('ر','رَ')
bassel4= bassel4:gsub('لا','لہا')
bassel4= bassel4:gsub('ى','ىْ')
bassel4= bassel4:gsub('ة','ة')
bassel4= bassel4:gsub('و','وِٰ')
bassel4= bassel4:gsub('ز','زَٰ')
bassel4= bassel4:gsub('ظ','ظۗہٰٰ')
bassel4= bassel4:gsub('q','𝑸')
bassel4= bassel4:gsub('Q','𝑸')
bassel4= bassel4:gsub('w','𝑾')
bassel4= bassel4:gsub('W','𝑾')
bassel4= bassel4:gsub('e','𝑬')
bassel4= bassel4:gsub('E','𝑬')
bassel4= bassel4:gsub('r','𝑹')
bassel4= bassel4:gsub('R','𝑹')
bassel4= bassel4:gsub('t','𝑻')
bassel4= bassel4:gsub('T','𝑻')
bassel4= bassel4:gsub('y','𝒀')
bassel4= bassel4:gsub('Y','𝒀')
bassel4= bassel4:gsub('u','𝑼')
bassel4= bassel4:gsub('U','𝑼')
bassel4= bassel4:gsub('i','𝑰')
bassel4= bassel4:gsub('I','𝑰')
bassel4= bassel4:gsub('o','𝑶')
bassel4= bassel4:gsub('O','𝑶')
bassel4= bassel4:gsub('p','𝑷')
bassel4= bassel4:gsub('P','𝑷')
bassel4= bassel4:gsub('a','𝑨')
bassel4= bassel4:gsub('A','𝑨')
bassel4= bassel4:gsub('s','𝑺')
bassel4= bassel4:gsub('S','𝑺')
bassel4= bassel4:gsub('d','𝑫')
bassel4= bassel4:gsub('D','𝑫')
bassel4= bassel4:gsub('f','𝑭')
bassel4= bassel4:gsub('F','𝑭')
bassel4= bassel4:gsub('g','𝑮')
bassel4= bassel4:gsub('G','𝑮')
bassel4= bassel4:gsub('h','𝑯')
bassel4= bassel4:gsub('H','𝑯')
bassel4= bassel4:gsub('j','𝑱')
bassel4= bassel4:gsub('J','𝑱')
bassel4= bassel4:gsub('k','𝑲')
bassel4= bassel4:gsub('K','𝑲')
bassel4= bassel4:gsub('l','𝑳')
bassel4= bassel4:gsub('L','𝑳')
bassel4= bassel4:gsub('z','𝒁')
bassel4= bassel4:gsub('Z','𝒁')
bassel4= bassel4:gsub('x','𝑿')
bassel4= bassel4:gsub('X','𝑿')
bassel4= bassel4:gsub('c','𝑪')
bassel4= bassel4:gsub('C','𝑪')
bassel4= bassel4:gsub('v','𝑽')
bassel4= bassel4:gsub('V','𝑽')
bassel4= bassel4:gsub('b','𝑩')
bassel4= bassel4:gsub('B','𝑩')
bassel4= bassel4:gsub('n','𝑵')
bassel4= bassel4:gsub('N','𝑵')
bassel4= bassel4:gsub('m','𝑴')
bassel4= bassel4:gsub('M','𝑴')



local bassel5= Text:gsub('ض','ضَ')
bassel5= bassel5:gsub('ص','صً')
bassel5= bassel5:gsub('ث','ثَ')
bassel5= bassel5:gsub('ق','قُ')
bassel5= bassel5:gsub('ف','فّ')
bassel5= bassel5:gsub('غ','غِ')
bassel5= bassel5:gsub('ع','عُ')
bassel5= bassel5:gsub('ه','ﮭ')
bassel5= bassel5:gsub('خ','خِ')
bassel5= bassel5:gsub('ح','حٌ')
bassel5= bassel5:gsub('ج','جُ')
bassel5= bassel5:gsub('د','دِ')
bassel5= bassel5:gsub('ذ','ذَ')
bassel5= bassel5:gsub('ش','شِ')
bassel5= bassel5:gsub('س','سً')
bassel5= bassel5:gsub('ي','يْ')
bassel5= bassel5:gsub('ب','بّ')
bassel5= bassel5:gsub('ل','لَ')
bassel5= bassel5:gsub('ا','أُ')
bassel5= bassel5:gsub('ت','تٌ')
bassel5= bassel5:gsub('ن','نً')
bassel5= bassel5:gsub('م','مِ')
bassel5= bassel5:gsub('ك','ڳّ')
bassel5= bassel5:gsub('ط','طٌ')
bassel5= bassel5:gsub('ئ','ئ')
bassel5= bassel5:gsub('ء','ء')
bassel5= bassel5:gsub('ؤ','ؤ')
bassel5= bassel5:gsub('ر','رٌ')
bassel5= bassel5:gsub('لا','لٌأً')
bassel5= bassel5:gsub('ى','ى')
bassel5= bassel5:gsub('ة','ةَ')
bassel5= bassel5:gsub('و','وِ')
bassel5= bassel5:gsub('ز','زُ')
bassel5= bassel5:gsub('ظ','ظ')
bassel5= bassel5:gsub('q','𝒒')
bassel5= bassel5:gsub('Q','𝒒')
bassel5= bassel5:gsub('w','𝒘')
bassel5= bassel5:gsub('W','𝒘')
bassel5= bassel5:gsub('e','𝒆')
bassel5= bassel5:gsub('E','𝒆')
bassel5= bassel5:gsub('r','𝒓')
bassel5= bassel5:gsub('R','𝒓')
bassel5= bassel5:gsub('t','𝒕')
bassel5= bassel5:gsub('T','𝒕')
bassel5= bassel5:gsub('y','𝒚')
bassel5= bassel5:gsub('Y','𝒚')
bassel5= bassel5:gsub('u','𝒖')
bassel5= bassel5:gsub('U','𝒖')
bassel5= bassel5:gsub('i','𝒊')
bassel5= bassel5:gsub('I','𝒊')
bassel5= bassel5:gsub('o','𝒐')
bassel5= bassel5:gsub('O','𝒐')
bassel5= bassel5:gsub('p','𝒑')
bassel5= bassel5:gsub('P','𝒑')
bassel5= bassel5:gsub('a','𝒂')
bassel5= bassel5:gsub('A','𝒂')
bassel5= bassel5:gsub('s','𝒔')
bassel5= bassel5:gsub('S','𝒔')
bassel5= bassel5:gsub('d','𝒅')
bassel5= bassel5:gsub('D','𝒅')
bassel5= bassel5:gsub('f','𝒇')
bassel5= bassel5:gsub('F','𝒇')
bassel5= bassel5:gsub('g','𝒈')
bassel5= bassel5:gsub('G','𝒈')
bassel5= bassel5:gsub('h','𝒉')
bassel5= bassel5:gsub('H','𝒉')
bassel5= bassel5:gsub('j','𝒋')
bassel5= bassel5:gsub('J','𝒋')
bassel5= bassel5:gsub('K','𝒌')
bassel5= bassel5:gsub('k','𝒌')
bassel5= bassel5:gsub('L','𝒍')
bassel5= bassel5:gsub('l','𝒍')
bassel5= bassel5:gsub('z','𝒛')
bassel5= bassel5:gsub('Z','𝒛')
bassel5= bassel5:gsub('x','𝒙')
bassel5= bassel5:gsub('X','𝒙')
bassel5= bassel5:gsub('c','𝒄')
bassel5= bassel5:gsub('C','𝒄')
bassel5= bassel5:gsub('v','𝒗')
bassel5= bassel5:gsub('V','𝒗')
bassel5= bassel5:gsub('b','𝒃')
bassel5= bassel5:gsub('B','𝒃')
bassel5= bassel5:gsub('n','𝒏')
bassel5= bassel5:gsub('N','𝒏')
bassel5= bassel5:gsub('m','𝒎')
bassel5= bassel5:gsub('M','𝒎')



local bassel6= Text:gsub('ض','ﺿ̭͠')
bassel6= bassel6:gsub('ص','ﺻ͡')
bassel6= bassel6:gsub('ث','ﺜ̲')
bassel6= bassel6:gsub('ق','ﭰ')
bassel6= bassel6:gsub('ف','ﻓ̲')
bassel6= bassel6:gsub('غ','ﻏ̲')
bassel6= bassel6:gsub('ع','ﻌ̲')
bassel6= bassel6:gsub('ه','ﮬ̲̌')
bassel6= bassel6:gsub('خ','خٌ')
bassel6= bassel6:gsub('ح','ﺣ̅')
bassel6= bassel6:gsub('ج','جُ')
bassel6= bassel6:gsub('د','ډ̝')
bassel6= bassel6:gsub('ذ','ذً')
bassel6= bassel6:gsub('ش','ﺷ̲')
bassel6= bassel6:gsub('س','ﺳ̉')
bassel6= bassel6:gsub('ي','ﯾ̃̐')
bassel6= bassel6:gsub('ب','ﺑ̲')
bassel6= bassel6:gsub('ل','ا̄ﻟ')
bassel6= bassel6:gsub('ا','ﺈ̃')
bassel6= bassel6:gsub('ت','ټُ')
bassel6= bassel6:gsub('ن','ﻧ̲')
bassel6= bassel6:gsub('م','ﻣ̲̉')
bassel6= bassel6:gsub('ك','گ')
bassel6= bassel6:gsub('ط','ﻁ̲')
bassel6= bassel6:gsub('ئ',' ْٰئ')
bassel6= bassel6:gsub('ء','ء')
bassel6= bassel6:gsub('ؤ','ؤ')
bassel6= bassel6:gsub('ر','ہڕ')
bassel6= bassel6:gsub('لا','ﻟ̲ﺂ̲')
bassel6= bassel6:gsub('ى','ى')
bassel6= bassel6:gsub('ة','ة')
bassel6= bassel6:gsub('و','ۇۈۉ')
bassel6= bassel6:gsub('ز','زُ')
bassel6= bassel6:gsub('ظ','ﻇ̲')
bassel6= bassel6:gsub('q','ǫ')
bassel6= bassel6:gsub('Q','ǫ')
bassel6= bassel6:gsub('w','ᴡ')
bassel6= bassel6:gsub('W','ᴡ')
bassel6= bassel6:gsub('e','ᴇ')
bassel6= bassel6:gsub('E','ᴇ')
bassel6= bassel6:gsub('r','ʀ')
bassel6= bassel6:gsub('R','ʀ')
bassel6= bassel6:gsub('t','ᴛ')
bassel6= bassel6:gsub('T','ᴛ')
bassel6= bassel6:gsub('y','ʏ')
bassel6= bassel6:gsub('Y','ʏ')
bassel6= bassel6:gsub('u','ụ')
bassel6= bassel6:gsub('U','ụ')
bassel6= bassel6:gsub('i','ɪ')
bassel6= bassel6:gsub('I','ɪ')
bassel6= bassel6:gsub('o','ᴏ')
bassel6= bassel6:gsub('O','ᴏ')
bassel6= bassel6:gsub('p','ᴘ')
bassel6= bassel6:gsub('P','ᴘ')
bassel6= bassel6:gsub('a','ᴀ')
bassel6= bassel6:gsub('A','ᴀ')
bassel6= bassel6:gsub('s','ѕ')
bassel6= bassel6:gsub('S','ѕ')
bassel6= bassel6:gsub('d','ᴅ')
bassel6= bassel6:gsub('D','ᴅ')
bassel6= bassel6:gsub('f','ғ')
bassel6= bassel6:gsub('F','ғ')
bassel6= bassel6:gsub('g','ɢ')
bassel6= bassel6:gsub('G','ɢ')
bassel6= bassel6:gsub('h','ʜ')
bassel6= bassel6:gsub('H','ʜ')
bassel6= bassel6:gsub('j','ᴊ')
bassel6= bassel6:gsub('J','ᴊ')
bassel6= bassel6:gsub('K','ᴋ')
bassel6= bassel6:gsub('k','ᴋ')
bassel6= bassel6:gsub('L','ʟ')
bassel6= bassel6:gsub('l','ʟ')
bassel6= bassel6:gsub('z','ᴢ')
bassel6= bassel6:gsub('Z','ᴢ')
bassel6= bassel6:gsub('x','х')
bassel6= bassel6:gsub('X','х')
bassel6= bassel6:gsub('c','ᴄ')
bassel6= bassel6:gsub('C','ᴄ')
bassel6= bassel6:gsub('v','ᴠ')
bassel6= bassel6:gsub('V','ᴠ')
bassel6= bassel6:gsub('b','ʙ')
bassel6= bassel6:gsub('B','ʙ')
bassel6= bassel6:gsub('n','ɴ')
bassel6= bassel6:gsub('N','ɴ')
bassel6= bassel6:gsub('m','ᴍ')
bassel6= bassel6:gsub('M','ᴍ')



local bassel7= Text:gsub('ض','ﺿ')
bassel7= bassel7:gsub('ص','ﺻ')
bassel7= bassel7:gsub('ث','ﭥ')
bassel7= bassel7:gsub('ق','ﻗ̮ـ̃')
bassel7= bassel7:gsub('ف','ﭬ')
bassel7= bassel7:gsub('غ','ﻏ̣̐')
bassel7= bassel7:gsub('ع','ﻋ')
bassel7= bassel7:gsub('ه','ھَہّ')
bassel7= bassel7:gsub('خ','ﺧ')
bassel7= bassel7:gsub('ح','פ')
bassel7= bassel7:gsub('ج','ﭴ')
bassel7= bassel7:gsub('د','ﮃ')
bassel7= bassel7:gsub('ذ','ذ')
bassel7= bassel7:gsub('ش','ﺷ')
bassel7= bassel7:gsub('س','ﺳ')
bassel7= bassel7:gsub('ي','ﯾ')
bassel7= bassel7:gsub('ب','ﺑ')
bassel7= bassel7:gsub('ل','ﻟ')
bassel7= bassel7:gsub('ا','ﺂ')
bassel7= bassel7:gsub('ت','ﭠ')
bassel7= bassel7:gsub('ن','ﻧ')
bassel7= bassel7:gsub('م','ﻣ̝̚')
bassel7= bassel7:gsub('ك','گـ')
bassel7= bassel7:gsub('ط','ﻁْ')
bassel7= bassel7:gsub('ئ','ٰئـ')
bassel7= bassel7:gsub('ء','ء')
bassel7= bassel7:gsub('ؤ','ﯗ')
bassel7= bassel7:gsub('ر','ړُ')
bassel7= bassel7:gsub('لا','ﻟآ')
bassel7= bassel7:gsub('ى','ـﮯ')
bassel7= bassel7:gsub('ة','ة')
bassel7= bassel7:gsub('و','ۆ')
bassel7= bassel7:gsub('ز','ژ')
bassel7= bassel7:gsub('ظ','ﻅ')
bassel7= bassel7:gsub('q','𝘘')
bassel7= bassel7:gsub('Q','𝘘')
bassel7= bassel7:gsub('w','𝘞')
bassel7= bassel7:gsub('W','𝘞')
bassel7= bassel7:gsub('e','𝘌')
bassel7= bassel7:gsub('E','𝘌')
bassel7= bassel7:gsub('r','𝘙')
bassel7= bassel7:gsub('R','𝘙')
bassel7= bassel7:gsub('t','𝘛')
bassel7= bassel7:gsub('T','𝘛')
bassel7= bassel7:gsub('y','𝘠')
bassel7= bassel7:gsub('Y','𝘠')
bassel7= bassel7:gsub('u','𝘜')
bassel7= bassel7:gsub('U','𝘜')
bassel7= bassel7:gsub('i','𝘐')
bassel7= bassel7:gsub('I','𝘐')
bassel7= bassel7:gsub('o','𝘖')
bassel7= bassel7:gsub('O','𝘖')
bassel7= bassel7:gsub('p','𝘗')
bassel7= bassel7:gsub('P','𝘗')
bassel7= bassel7:gsub('a','𝘈')
bassel7= bassel7:gsub('A','𝘈')
bassel7= bassel7:gsub('s','𝘚')
bassel7= bassel7:gsub('S','𝘚')
bassel7= bassel7:gsub('d','𝘋')
bassel7= bassel7:gsub('D','𝘋')
bassel7= bassel7:gsub('f','𝘍')
bassel7= bassel7:gsub('F','𝘍')
bassel7= bassel7:gsub('g','𝘎')
bassel7= bassel7:gsub('G','𝘎')
bassel7= bassel7:gsub('h','𝘏')
bassel7= bassel7:gsub('H','𝘏')
bassel7= bassel7:gsub('j','𝘑')
bassel7= bassel7:gsub('J','𝘑')
bassel7= bassel7:gsub('k','𝘒')
bassel7= bassel7:gsub('K','𝘒')
bassel7= bassel7:gsub('L','𝘓')
bassel7= bassel7:gsub('l','𝘓')
bassel7= bassel7:gsub('z','𝘡')
bassel7= bassel7:gsub('Z','𝘡')
bassel7= bassel7:gsub('x','𝘟')
bassel7= bassel7:gsub('X','𝘟')
bassel7= bassel7:gsub('c','𝘊')
bassel7= bassel7:gsub('C','𝘊')
bassel7= bassel7:gsub('v','𝘝')
bassel7= bassel7:gsub('V','𝘝')
bassel7= bassel7:gsub('b','𝘉')
bassel7= bassel7:gsub('B','𝘉')
bassel7= bassel7:gsub('n','𝘕')
bassel7= bassel7:gsub('N','𝘕')
bassel7= bassel7:gsub('m','𝘔')
bassel7= bassel7:gsub('M','𝘔')



local bassel8= Text:gsub('ض','ض');
bassel8= bassel8:gsub('ص','صہٰ')
bassel8= bassel8:gsub('ث','ثہٰـ')
bassel8= bassel8:gsub('ق','قہٰ')
bassel8= bassel8:gsub('ف','فہٰ')
bassel8= bassel8:gsub('غ','غـْ')
bassel8= bassel8:gsub('ع','ع')
bassel8= bassel8:gsub('ه','هٰہٰٖ')
bassel8= bassel8:gsub('خ','خخَـ')
bassel8= bassel8:gsub('ح','حہٰ')
bassel8= bassel8:gsub('ج','ججہٰ')
bassel8= bassel8:gsub('د','دَ')
bassel8= bassel8:gsub('ذ','ذّ')
bassel8= bassel8:gsub('ش','ششہٰ')
bassel8= bassel8:gsub('س','سہٰ')
bassel8= bassel8:gsub('ي','يٰ')
bassel8= bassel8:gsub('ب','بٰٰ')
bassel8= bassel8:gsub('ل','لہٰ')
bassel8= bassel8:gsub('ا','آ')
bassel8= bassel8:gsub('ت','تہٰ')
bassel8= bassel8:gsub('ن','نہٰ')
bassel8= bassel8:gsub('م','مہٰ')
bassel8= bassel8:gsub('ك','ككہٰ')
bassel8= bassel8:gsub('ط','طہٰ')
bassel8= bassel8:gsub('ئ',' ْئٰ')
bassel8= bassel8:gsub('ء','ء')
bassel8= bassel8:gsub('ؤ','ؤؤَ')
bassel8= bassel8:gsub('ر','رَ')
bassel8= bassel8:gsub('لا','لہٰا')
bassel8= bassel8:gsub('ى','ىہٰ')
bassel8= bassel8:gsub('ة','ة')
bassel8= bassel8:gsub('و','ہٰو')
bassel8= bassel8:gsub('ز','ز')
bassel8= bassel8:gsub('ظ','ظہٰ')
bassel8= bassel8:gsub('q','𝚀')
bassel8= bassel8:gsub('Q','𝚀')
bassel8= bassel8:gsub('w','𝚆')
bassel8= bassel8:gsub('W','𝚆')
bassel8= bassel8:gsub('e','𝙴')
bassel8= bassel8:gsub('E','𝙴')
bassel8= bassel8:gsub('r','𝚁')
bassel8= bassel8:gsub('R','𝚁')
bassel8= bassel8:gsub('t','𝚃')
bassel8= bassel8:gsub('T','𝚃')
bassel8= bassel8:gsub('y','𝚈')
bassel8= bassel8:gsub('Y','𝚈')
bassel8= bassel8:gsub('u','𝚄')
bassel8= bassel8:gsub('U','𝚄')
bassel8= bassel8:gsub('i','𝙸')
bassel8= bassel8:gsub('I','𝙸')
bassel8= bassel8:gsub('o','𝙾')
bassel8= bassel8:gsub('O','𝙾')
bassel8= bassel8:gsub('p','𝙿')
bassel8= bassel8:gsub('P','𝙿')
bassel8= bassel8:gsub('a','𝙰')
bassel8= bassel8:gsub('A','𝙰')
bassel8= bassel8:gsub('s','𝚂')
bassel8= bassel8:gsub('S','𝚂')
bassel8= bassel8:gsub('d','𝙳')
bassel8= bassel8:gsub('D','𝙳')
bassel8= bassel8:gsub('f','𝙵')
bassel8= bassel8:gsub('F','𝙵')
bassel8= bassel8:gsub('g','𝙶')
bassel8= bassel8:gsub('G','𝙶')
bassel8= bassel8:gsub('h','𝙷')
bassel8= bassel8:gsub('H','𝙷')
bassel8= bassel8:gsub('j','𝙹')
bassel8= bassel8:gsub('J','𝙹')
bassel8= bassel8:gsub('k','𝙺')
bassel8= bassel8:gsub('K','𝙺')
bassel8= bassel8:gsub('L','𝙻')
bassel8= bassel8:gsub('l','𝙻')
bassel8= bassel8:gsub('z','𝚉')
bassel8= bassel8:gsub('Z','𝚉')
bassel8= bassel8:gsub('x','𝚇')
bassel8= bassel8:gsub('X','𝚇')
bassel8= bassel8:gsub('c','𝙲')
bassel8= bassel8:gsub('C','𝙲')
bassel8= bassel8:gsub('v','𝚅')
bassel8= bassel8:gsub('V','𝚅')
bassel8= bassel8:gsub('b','𝙱')
bassel8= bassel8:gsub('B','𝙱')
bassel8= bassel8:gsub('n','𝙽')
bassel8= bassel8:gsub('N','𝙽')
bassel8= bassel8:gsub('m','𝙼')
bassel8= bassel8:gsub('M','𝙼')



local bassel9= Text:gsub('ض','ض')
bassel9= bassel9:gsub('ص','ص')
bassel9= bassel9:gsub('ث','ث')
bassel9= bassel9:gsub('ق','قٌ')
bassel9= bassel9:gsub('ف','فُ')
bassel9= bassel9:gsub('غ','غ')
bassel9= bassel9:gsub('ع','عٍ')
bassel9= bassel9:gsub('ه','هـ')
bassel9= bassel9:gsub('خ','خـ')
bassel9= bassel9:gsub('ح','حٍ')
bassel9= bassel9:gsub('ج','جٍ')
bassel9= bassel9:gsub('د','دِ')
bassel9= bassel9:gsub('ذ','ذَ')
bassel9= bassel9:gsub('ش','شُ')
bassel9= bassel9:gsub('س','س')
bassel9= bassel9:gsub('ي','ي')
bassel9= bassel9:gsub('ب','بَ')
bassel9= bassel9:gsub('ل','لُِ')
bassel9= bassel9:gsub('ا','آ')
bassel9= bassel9:gsub('ت','ت')
bassel9= bassel9:gsub('ن','ن')
bassel9= bassel9:gsub('م','م')
bassel9= bassel9:gsub('ك','ڪ')
bassel9= bassel9:gsub('ط','طُ')
bassel9= bassel9:gsub('ئ','ئ ْٰ')
bassel9= bassel9:gsub('ء','ء')
bassel9= bassel9:gsub('ؤ','ؤ')
bassel9= bassel9:gsub('ر','ر')
bassel9= bassel9:gsub('لا','لُِآ')
bassel9= bassel9:gsub('ى','ىْ')
bassel9= bassel9:gsub('ة','ة')
bassel9= bassel9:gsub('و','وو')
bassel9= bassel9:gsub('ز','ز')
bassel9= bassel9:gsub('ظ','ظهُ')
bassel9= bassel9:gsub('q','ℚ')
bassel9= bassel9:gsub('Q','ℚ')
bassel9= bassel9:gsub('w','𝕎')
bassel9= bassel9:gsub('W','𝕎')
bassel9= bassel9:gsub('e','𝔼')
bassel9= bassel9:gsub('E','𝔼')
bassel9= bassel9:gsub('r','ℝ')
bassel9= bassel9:gsub('R','ℝ')
bassel9= bassel9:gsub('t','𝕋')
bassel9= bassel9:gsub('T','𝕋')
bassel9= bassel9:gsub('y','𝕐')
bassel9= bassel9:gsub('Y','𝕐')
bassel9= bassel9:gsub('u','𝕌')
bassel9= bassel9:gsub('U','𝕌')
bassel9= bassel9:gsub('i','𝕀')
bassel9= bassel9:gsub('I','𝕀')
bassel9= bassel9:gsub('o','𝕆')
bassel9= bassel9:gsub('O','𝕆')
bassel9= bassel9:gsub('p','ℙ')
bassel9= bassel9:gsub('P','ℙ')
bassel9= bassel9:gsub('a','𝔸')
bassel9= bassel9:gsub('A','𝔸')
bassel9= bassel9:gsub('s','𝕊')
bassel9= bassel9:gsub('S','𝕊')
bassel9= bassel9:gsub('d','𝔻')
bassel9= bassel9:gsub('D','𝔻')
bassel9= bassel9:gsub('f','𝔽')
bassel9= bassel9:gsub('F','𝔽')
bassel9= bassel9:gsub('g','𝔾')
bassel9= bassel9:gsub('G','𝔾')
bassel9= bassel9:gsub('h','ℍ')
bassel9= bassel9:gsub('H','ℍ')
bassel9= bassel9:gsub('j','𝕁')
bassel9= bassel9:gsub('J','𝕁')
bassel9= bassel9:gsub('k','𝕂')
bassel9= bassel9:gsub('K','𝕂')
bassel9= bassel9:gsub('L','𝕃')
bassel9= bassel9:gsub('l','𝕃')
bassel9= bassel9:gsub('z','ℤ')
bassel9= bassel9:gsub('Z','ℤ')
bassel9= bassel9:gsub('x','𝕏')
bassel9= bassel9:gsub('X','𝕏')
bassel9= bassel9:gsub('c','ℂ')
bassel9= bassel9:gsub('C','ℂ')
bassel9= bassel9:gsub('v','𝕍')
bassel9= bassel9:gsub('V','𝕍')
bassel9= bassel9:gsub('b','𝔹')
bassel9= bassel9:gsub('B','𝔹')
bassel9= bassel9:gsub('n','ℕ')
bassel9= bassel9:gsub('N','ℕ')
bassel9= bassel9:gsub('m','𝕄')
bassel9= bassel9:gsub('M','𝕄')


local Text_bassela = "1- `"..bassel..EmojeS[math.random(#EmojeS)]
.."`\n\n2- `"..bassel2..EmojeS[math.random(#EmojeS)]
.."`\n\n3- `"..bassel3..EmojeS[math.random(#EmojeS)]
.."`\n\n4- `"..bassel4..EmojeS[math.random(#EmojeS)]
.."`\n\n5- `"..bassel5..EmojeS[math.random(#EmojeS)]
.."`\n\n6- `"..bassel6..EmojeS[math.random(#EmojeS)]
.."`\n\n7- `"..bassel7..EmojeS[math.random(#EmojeS)]
.."`\n\n8- `"..bassel8..Emoje[math.random(#Emoje)]
.."`\n\n9- `"..bassel9..Emoje[math.random(#Emoje)]
.."`\n\n10- `"..bassel5..Emoje[math.random(#Emoje)]
Text_bassela = Text_bassela.."`\n\n اضغط علـي الاسـم ليـتم النـسخ \n★"
sendMsg(msg.chat_id_,msg.id_,Text_bassela)
return false
end
end

end
local function TextRes(msg)

if msg.text and msg.type ~= "pv" and redis:get(black..":basselNow:"..msg.sender_user_id_) then
Text = msg.text
redis:del(black..":basselNow:"..msg.sender_user_id_)
if utf8.len(msg.text) > 300 then
sendMsg(msg.chat_id_,msg.id_," لا يمكنك زخرفه اكثر من 300 حرف \n  ارسل امر زخرفه وحاول مجددا بحروف اقل")    
return false
end
local EmojeS = {
' 𓁻',
' 𓏴  ',
' 𓏶 ',
' 𓏡',
' 𓏢', 
' 𓏣', 
' ☽‘',
' 𖠱²²', 
'▽', 
' 𖡛“', 
' 𖡚℡', 
' 𖡨', 
}

local Emoje = {
' ♕',
' 𖤍',
'˛𖤓',
' ཻ ☫',
' ♫ ',
' 𖠶 ',
' 𖠲',
' 𖡥',
'  ☬',
' 𖤐',
' 𓇼',
' ♘  '
}


local bassel = Text:gsub('ض','ضِٰـِۢ')
bassel = bassel:gsub('ص','صِٰـِۢ')
bassel = bassel:gsub('ث','ثِٰـِۢ')
bassel = bassel:gsub('ق','قِٰـِۢ')
bassel = bassel:gsub('ف','فِٰ͒ـِۢ')
bassel = bassel:gsub('غ','غِٰـِۢ')
bassel = bassel:gsub('ع','عِٰـِۢ')
bassel = bassel:gsub('خ','خِٰ̐ـِۢ')
bassel = bassel:gsub('ح','حِٰـِۢ')
bassel = bassel:gsub('ج','جِٰـِۢ')
bassel = bassel:gsub('ش','شِٰـِۢ')
bassel = bassel:gsub('س','سِٰـِۢ')
bassel = bassel:gsub('ي','يِٰـِۢ')
bassel = bassel:gsub('ب','بِٰـِۢ')
bassel = bassel:gsub('ل','لِٰـِۢ')
bassel = bassel:gsub('ا','آ')
bassel = bassel:gsub('ت','تِٰـِۢ')
bassel = bassel:gsub('ن','نِٰـِۢ')
bassel = bassel:gsub('م','مِٰـِۢ')
bassel = bassel:gsub('ك','ڪِٰـِۢ')
bassel = bassel:gsub('ط','طِٰـِۢ')
bassel = bassel:gsub('ظ','ظِٰـِۢ')
bassel = bassel:gsub('ء','ء')
bassel = bassel:gsub('ؤ','ؤ')
bassel = bassel:gsub('ر','ر')
bassel = bassel:gsub('ى','ى')
bassel = bassel:gsub('ز','ز')
bassel = bassel:gsub('و','ﯛ̲୭')
bassel = bassel:gsub('ه','ۿۿہ')
bassel = bassel:gsub('a','𝗮')
bassel = bassel:gsub('A','𝗔')
bassel = bassel:gsub("b","𝗯")
bassel = bassel:gsub("B","𝗕")
bassel = bassel:gsub("c","𝗰")
bassel = bassel:gsub("C","𝗖")
bassel = bassel:gsub("d","𝗱")
bassel = bassel:gsub("D","𝗗")
bassel = bassel:gsub("e","𝗲")
bassel = bassel:gsub("E","𝗘")
bassel = bassel:gsub("f","𝗳")
bassel = bassel:gsub("F","𝗙")
bassel = bassel:gsub("g","𝗴")
bassel = bassel:gsub("G","𝗚")
bassel = bassel:gsub("h","𝗵")
bassel = bassel:gsub("H","𝗛")
bassel = bassel:gsub("i","𝗹")
bassel = bassel:gsub("I","𝗜")
bassel = bassel:gsub("j","𝗝")
bassel = bassel:gsub("J","𝗝")
bassel = bassel:gsub("k","𝗸")
bassel = bassel:gsub("K","𝗞")
bassel = bassel:gsub("l","𝗹")
bassel = bassel:gsub("L","𝗟")
bassel = bassel:gsub("m","𝗺")
bassel = bassel:gsub("M","𝗠")
bassel = bassel:gsub("n","𝗻")
bassel = bassel:gsub("N","𝗡")
bassel = bassel:gsub("o","𝗼")
bassel = bassel:gsub("O","𝗢")
bassel = bassel:gsub("p","𝗽")
bassel = bassel:gsub("P","𝗣")
bassel = bassel:gsub("q","𝗾")
bassel = bassel:gsub("Q","𝗤")
bassel = bassel:gsub("r","𝗿")
bassel = bassel:gsub("R","𝗥")
bassel = bassel:gsub("s","𝘀")
bassel = bassel:gsub("S","𝗦")
bassel = bassel:gsub("t","𝘁")
bassel = bassel:gsub("T","𝗧")
bassel = bassel:gsub("u","𝘂")
bassel = bassel:gsub("U","𝗨")
bassel = bassel:gsub("v","𝘃")
bassel = bassel:gsub("V","𝗩")
bassel = bassel:gsub("w","𝘄")
bassel = bassel:gsub("W","𝗪")
bassel = bassel:gsub("x","𝘅")
bassel = bassel:gsub("X","𝗫")
bassel = bassel:gsub("y","𝘆")
bassel = bassel:gsub("Y","𝗬")
bassel = bassel:gsub("z","𝘇")
bassel = bassel:gsub("Z","𝗭")



local bassel2 = Text:gsub('ض','ضَٰـُـٰٓ')
bassel2 = bassel2:gsub('ص','صَٰـُـٰٓ')
bassel2 = bassel2:gsub('ث','ثَٰـُـٰٓ')
bassel2 = bassel2:gsub('ق','قَٰـُـٰٓ')
bassel2 = bassel2:gsub('ف','فَٰ͒ـُـٰٓ')
bassel2 = bassel2:gsub('غ','غَٰـُـٰٓ')
bassel2 = bassel2:gsub('ع','عَٰـُـٰٓ')
bassel2 = bassel2:gsub('خ','خَٰ̐ـُـٰٓ')
bassel2 = bassel2:gsub('ح','حَٰـُـٰٓ')
bassel2 = bassel2:gsub('ج','جَٰـُـٰٓ')
bassel2 = bassel2:gsub('ش','شَٰـُـٰٓ')
bassel2 = bassel2:gsub('س','سَٰـُـٰٓ')
bassel2 = bassel2:gsub('ي','يَٰـُـٰٓ')
bassel2 = bassel2:gsub('ب','بَٰـُـٰٓ')
bassel2 = bassel2:gsub('ل','لَٰـُـٰٓ')
bassel2 = bassel2:gsub('ا','آ')
bassel2 = bassel2:gsub('ت','تَٰـُـٰٓ')
bassel2 = bassel2:gsub('ن','نَٰـُـٰٓ')
bassel2 = bassel2:gsub('م','مَٰـُـٰٓ')
bassel2 = bassel2:gsub('ك','ڪَٰـُـٰٓ')
bassel2 = bassel2:gsub('ط','طَٰـُـٰٓ')
bassel2 = bassel2:gsub('ظ','ظَٰـُـٰٓ')
bassel2 = bassel2:gsub('ء','ء')
bassel2 = bassel2:gsub('ؤ','ؤ')
bassel2 = bassel2:gsub('ر','ر')
bassel2 = bassel2:gsub('ى','ى')
bassel2 = bassel2:gsub('ز','ز')
bassel2 = bassel2:gsub('و','ﯛ̲୭')
bassel2 = bassel2:gsub("ه", "ۿۿہ")
bassel2 = bassel2:gsub('a',"𝖆")
bassel2 = bassel2:gsub('A',"𝖆")
bassel2 = bassel2:gsub("b","𝖇")
bassel2 = bassel2:gsub("B","𝖇")
bassel2 = bassel2:gsub("c","𝖈")
bassel2 = bassel2:gsub("C","𝖈")
bassel2 = bassel2:gsub("d","𝖉")
bassel2 = bassel2:gsub("D","𝖉")
bassel2 = bassel2:gsub("e","𝖊")
bassel2 = bassel2:gsub("E","𝖊")
bassel2 = bassel2:gsub("f","𝖋")
bassel2 = bassel2:gsub("F","𝖋")
bassel2 = bassel2:gsub("g","𝖌")
bassel2 = bassel2:gsub("G","𝖌")
bassel2 = bassel2:gsub("h","𝖍")
bassel2 = bassel2:gsub("H","𝖍")
bassel2 = bassel2:gsub("i","𝖎")
bassel2 = bassel2:gsub("I","𝖎")
bassel2 = bassel2:gsub("j","𝖏")
bassel2 = bassel2:gsub("J","𝖏")
bassel2 = bassel2:gsub("k","𝖐")
bassel2 = bassel2:gsub("K","𝖐")
bassel2 = bassel2:gsub("l","𝖑")
bassel2 = bassel2:gsub("L","𝖑")
bassel2 = bassel2:gsub("m","𝖒")
bassel2 = bassel2:gsub("M","𝖒")
bassel2 = bassel2:gsub("n","𝖓")
bassel2 = bassel2:gsub("N","𝖓")
bassel2 = bassel2:gsub("o","𝖔")
bassel2 = bassel2:gsub("O","𝖔")
bassel2 = bassel2:gsub("p","𝖕")
bassel2 = bassel2:gsub("P","𝖕")
bassel2 = bassel2:gsub("q","𝖖")
bassel2 = bassel2:gsub("Q","𝖖")
bassel2 = bassel2:gsub("r","𝖗")
bassel2 = bassel2:gsub("R","𝖗")
bassel2 = bassel2:gsub("s","𝖘")
bassel2 = bassel2:gsub("S","𝖘")
bassel2 = bassel2:gsub("t","𝖙")
bassel2 = bassel2:gsub("T","𝖙")
bassel2 = bassel2:gsub("u","𝖚")
bassel2 = bassel2:gsub("U","𝖚")
bassel2 = bassel2:gsub("v","𝖛")
bassel2 = bassel2:gsub("V","𝖛")
bassel2 = bassel2:gsub("w","𝖜")
bassel2 = bassel2:gsub("W","𝖜")
bassel2 = bassel2:gsub("x","𝖝")
bassel2 = bassel2:gsub("X","𝖝")
bassel2 = bassel2:gsub("y","𝖞")
bassel2 = bassel2:gsub("Y","𝖞")
bassel2 = bassel2:gsub("z","𝖟")
bassel2 = bassel2:gsub("Z","𝖟")


local bassel3= Text:gsub('ض','ض')
bassel3= bassel3:gsub('ص','ص')
bassel3= bassel3:gsub('ث','ثہ')
bassel3= bassel3:gsub('ق','ق')
bassel3= bassel3:gsub('ف','فُہ')
bassel3= bassel3:gsub('غ','غہ')
bassel3= bassel3:gsub('ع','عہ')
bassel3= bassel3:gsub('ه','هٰہٰٖ')
bassel3= bassel3:gsub('خ','خہ')
bassel3= bassel3:gsub('ح','حہ')
bassel3= bassel3:gsub('ج','جہ')
bassel3= bassel3:gsub('د','د')
bassel3= bassel3:gsub('ذ','ذ')
bassel3= bassel3:gsub('ش','شہ')
bassel3= bassel3:gsub('س','سہ')
bassel3= bassel3:gsub('ي','يہ')
bassel3= bassel3:gsub('ب','بّ')
bassel3= bassel3:gsub('ل','لہ')
bassel3= bassel3:gsub('ا','ا')
bassel3= bassel3:gsub('ت','تہ')
bassel3= bassel3:gsub('ن','نٰہٰٖ')
bassel3= bassel3:gsub('م','مٰہٰٖ')
bassel3= bassel3:gsub('ك','كُہ')
bassel3= bassel3:gsub('ط','طہ')
bassel3= bassel3:gsub('ئ','ئ ْٰ')
bassel3= bassel3:gsub('ء','ء')
bassel3= bassel3:gsub('ؤ','ؤ')
bassel3= bassel3:gsub('ر','رَ')
bassel3= bassel3:gsub('لا','لہا')
bassel3= bassel3:gsub('ى','ىْ')
bassel3= bassel3:gsub('ة','ة')
bassel3= bassel3:gsub('و','و')
bassel3= bassel3:gsub('ز','ز')
bassel3= bassel3:gsub('ظ','ظۗہٰٰ')
bassel3= bassel3:gsub('q','𝐪')
bassel3= bassel3:gsub('Q','𝐪')
bassel3= bassel3:gsub('w','𝐰')
bassel3= bassel3:gsub('W','𝐰')
bassel3= bassel3:gsub('e','𝐞')
bassel3= bassel3:gsub('E','𝐞')
bassel3= bassel3:gsub('r','𝐫')
bassel3= bassel3:gsub('R','𝐫')
bassel3= bassel3:gsub('t','𝐭')
bassel3= bassel3:gsub('T','𝐭')
bassel3= bassel3:gsub('y','𝐲')
bassel3= bassel3:gsub('Y','𝐲')
bassel3= bassel3:gsub('u','𝐮')
bassel3= bassel3:gsub('i','𝐢')
bassel3= bassel3:gsub('o','𝐨')
bassel3= bassel3:gsub('p','𝐩')
bassel3= bassel3:gsub('a','𝐚')
bassel3= bassel3:gsub('s','𝐬')
bassel3= bassel3:gsub('d','𝐝')
bassel3= bassel3:gsub('f','𝐟')
bassel3= bassel3:gsub('g','𝐠')
bassel3= bassel3:gsub('h','𝐡')
bassel3= bassel3:gsub('j','𝐣')
bassel3= bassel3:gsub('k','𝐤')
bassel3= bassel3:gsub('U','𝐮')
bassel3= bassel3:gsub('I','𝐢')
bassel3= bassel3:gsub('O','𝐨')
bassel3= bassel3:gsub('P','𝐩')
bassel3= bassel3:gsub('A','𝐚')
bassel3= bassel3:gsub('S','𝐬')
bassel3= bassel3:gsub('D','𝐝')
bassel3= bassel3:gsub('F','𝐟')
bassel3= bassel3:gsub('G','𝐠')
bassel3= bassel3:gsub('H','𝐡')
bassel3= bassel3:gsub('J','𝐣')
bassel3= bassel3:gsub('K','𝐤')
bassel3= bassel3:gsub('L','𝐥')
bassel3= bassel3:gsub('l','𝐥')
bassel3= bassel3:gsub('z','𝐳')
bassel3= bassel3:gsub('Z','𝐳')
bassel3= bassel3:gsub('x','𝐱')
bassel3= bassel3:gsub('X','ẋ')
bassel3= bassel3:gsub('c','𝐜')
bassel3= bassel3:gsub('C','𝐜')
bassel3= bassel3:gsub('v','𝐯')
bassel3= bassel3:gsub('V','𝐯')
bassel3= bassel3:gsub('b','𝐛')
bassel3= bassel3:gsub('B','𝐛')
bassel3= bassel3:gsub('n','𝐧')
bassel3= bassel3:gsub('N','𝐧')
bassel3= bassel3:gsub('m','𝐦')
bassel3= bassel3:gsub('M','𝐦')


local bassel4= Text:gsub('ض','ضۜہٰٰ')
bassel4= bassel4:gsub('ص','ضۜہٰٰ')
bassel4= bassel4:gsub('ث','ثہٰٰ')
bassel4= bassel4:gsub('ق','قྀ̲ہٰٰ')
bassel4= bassel4:gsub('ف','ف͒ہٰٰ')
bassel4= bassel4:gsub('غ','غہٰٰ')
bassel4= bassel4:gsub('ع','عہٰٰ')
bassel4= bassel4:gsub('ه','هٰہٰٖ')
bassel4= bassel4:gsub('خ','خٰ̐ہ ')
bassel4= bassel4:gsub('ح','حہٰٰ')
bassel4= bassel4:gsub('ج','جـٰ̲ـہْۧ')
bassel4= bassel4:gsub('د','دٰ')
bassel4= bassel4:gsub('ذ','ذِٰ')
bassel4= bassel4:gsub('ش','شِٰہٰٰ')
bassel4= bassel4:gsub('س','سٰٓ')
bassel4= bassel4:gsub('ي','يِٰہ')
bassel4= bassel4:gsub('ب','بّہ')
bassel4= bassel4:gsub('ل','لـٰ̲ـہ')
bassel4= bassel4:gsub('ا','آ')
bassel4= bassel4:gsub('ت','تَہَٰ')
bassel4= bassel4:gsub('ن','نَِہ')
bassel4= bassel4:gsub('م','مٰ̲ہ')
bassel4= bassel4:gsub('ك','ڪٰྀہٰٰ')
bassel4= bassel4:gsub('ط','طۨہٰٰ')
bassel4= bassel4:gsub('ئ','ئ ْٰ')
bassel4= bassel4:gsub('ء','ء')
bassel4= bassel4:gsub('ؤ','ؤ')
bassel4= bassel4:gsub('ر','رَ')
bassel4= bassel4:gsub('لا','لہا')
bassel4= bassel4:gsub('ى','ىْ')
bassel4= bassel4:gsub('ة','ة')
bassel4= bassel4:gsub('و','وِٰ')
bassel4= bassel4:gsub('ز','زَٰ')
bassel4= bassel4:gsub('ظ','ظۗہٰٰ')
bassel4= bassel4:gsub('q','𝑸')
bassel4= bassel4:gsub('Q','𝑸')
bassel4= bassel4:gsub('w','𝑾')
bassel4= bassel4:gsub('W','𝑾')
bassel4= bassel4:gsub('e','𝑬')
bassel4= bassel4:gsub('E','𝑬')
bassel4= bassel4:gsub('r','𝑹')
bassel4= bassel4:gsub('R','𝑹')
bassel4= bassel4:gsub('t','𝑻')
bassel4= bassel4:gsub('T','𝑻')
bassel4= bassel4:gsub('y','𝒀')
bassel4= bassel4:gsub('Y','𝒀')
bassel4= bassel4:gsub('u','𝑼')
bassel4= bassel4:gsub('U','𝑼')
bassel4= bassel4:gsub('i','𝑰')
bassel4= bassel4:gsub('I','𝑰')
bassel4= bassel4:gsub('o','𝑶')
bassel4= bassel4:gsub('O','𝑶')
bassel4= bassel4:gsub('p','𝑷')
bassel4= bassel4:gsub('P','𝑷')
bassel4= bassel4:gsub('a','𝑨')
bassel4= bassel4:gsub('A','𝑨')
bassel4= bassel4:gsub('s','𝑺')
bassel4= bassel4:gsub('S','𝑺')
bassel4= bassel4:gsub('d','𝑫')
bassel4= bassel4:gsub('D','𝑫')
bassel4= bassel4:gsub('f','𝑭')
bassel4= bassel4:gsub('F','𝑭')
bassel4= bassel4:gsub('g','𝑮')
bassel4= bassel4:gsub('G','𝑮')
bassel4= bassel4:gsub('h','𝑯')
bassel4= bassel4:gsub('H','𝑯')
bassel4= bassel4:gsub('j','𝑱')
bassel4= bassel4:gsub('J','𝑱')
bassel4= bassel4:gsub('k','𝑲')
bassel4= bassel4:gsub('K','𝑲')
bassel4= bassel4:gsub('l','𝑳')
bassel4= bassel4:gsub('L','𝑳')
bassel4= bassel4:gsub('z','𝒁')
bassel4= bassel4:gsub('Z','𝒁')
bassel4= bassel4:gsub('x','𝑿')
bassel4= bassel4:gsub('X','𝑿')
bassel4= bassel4:gsub('c','𝑪')
bassel4= bassel4:gsub('C','𝑪')
bassel4= bassel4:gsub('v','𝑽')
bassel4= bassel4:gsub('V','𝑽')
bassel4= bassel4:gsub('b','𝑩')
bassel4= bassel4:gsub('B','𝑩')
bassel4= bassel4:gsub('n','𝑵')
bassel4= bassel4:gsub('N','𝑵')
bassel4= bassel4:gsub('m','𝑴')
bassel4= bassel4:gsub('M','𝑴')



local bassel5= Text:gsub('ض','ضَ')
bassel5= bassel5:gsub('ص','صً')
bassel5= bassel5:gsub('ث','ثَ')
bassel5= bassel5:gsub('ق','قُ')
bassel5= bassel5:gsub('ف','فّ')
bassel5= bassel5:gsub('غ','غِ')
bassel5= bassel5:gsub('ع','عُ')
bassel5= bassel5:gsub('ه','ﮭ')
bassel5= bassel5:gsub('خ','خِ')
bassel5= bassel5:gsub('ح','حٌ')
bassel5= bassel5:gsub('ج','جُ')
bassel5= bassel5:gsub('د','دِ')
bassel5= bassel5:gsub('ذ','ذَ')
bassel5= bassel5:gsub('ش','شِ')
bassel5= bassel5:gsub('س','سً')
bassel5= bassel5:gsub('ي','يْ')
bassel5= bassel5:gsub('ب','بّ')
bassel5= bassel5:gsub('ل','لَ')
bassel5= bassel5:gsub('ا','أُ')
bassel5= bassel5:gsub('ت','تٌ')
bassel5= bassel5:gsub('ن','نً')
bassel5= bassel5:gsub('م','مِ')
bassel5= bassel5:gsub('ك','ڳّ')
bassel5= bassel5:gsub('ط','طٌ')
bassel5= bassel5:gsub('ئ','ئ')
bassel5= bassel5:gsub('ء','ء')
bassel5= bassel5:gsub('ؤ','ؤ')
bassel5= bassel5:gsub('ر','رٌ')
bassel5= bassel5:gsub('لا','لٌأً')
bassel5= bassel5:gsub('ى','ى')
bassel5= bassel5:gsub('ة','ةَ')
bassel5= bassel5:gsub('و','وِ')
bassel5= bassel5:gsub('ز','زُ')
bassel5= bassel5:gsub('ظ','ظ')
bassel5= bassel5:gsub('q','𝒒')
bassel5= bassel5:gsub('Q','𝒒')
bassel5= bassel5:gsub('w','𝒘')
bassel5= bassel5:gsub('W','𝒘')
bassel5= bassel5:gsub('e','𝒆')
bassel5= bassel5:gsub('E','𝒆')
bassel5= bassel5:gsub('r','𝒓')
bassel5= bassel5:gsub('R','𝒓')
bassel5= bassel5:gsub('t','𝒕')
bassel5= bassel5:gsub('T','𝒕')
bassel5= bassel5:gsub('y','𝒚')
bassel5= bassel5:gsub('Y','𝒚')
bassel5= bassel5:gsub('u','𝒖')
bassel5= bassel5:gsub('U','𝒖')
bassel5= bassel5:gsub('i','𝒊')
bassel5= bassel5:gsub('I','𝒊')
bassel5= bassel5:gsub('o','𝒐')
bassel5= bassel5:gsub('O','𝒐')
bassel5= bassel5:gsub('p','𝒑')
bassel5= bassel5:gsub('P','𝒑')
bassel5= bassel5:gsub('a','𝒂')
bassel5= bassel5:gsub('A','𝒂')
bassel5= bassel5:gsub('s','𝒔')
bassel5= bassel5:gsub('S','𝒔')
bassel5= bassel5:gsub('d','𝒅')
bassel5= bassel5:gsub('D','𝒅')
bassel5= bassel5:gsub('f','𝒇')
bassel5= bassel5:gsub('F','𝒇')
bassel5= bassel5:gsub('g','𝒈')
bassel5= bassel5:gsub('G','𝒈')
bassel5= bassel5:gsub('h','𝒉')
bassel5= bassel5:gsub('H','𝒉')
bassel5= bassel5:gsub('j','𝒋')
bassel5= bassel5:gsub('J','𝒋')
bassel5= bassel5:gsub('K','𝒌')
bassel5= bassel5:gsub('k','𝒌')
bassel5= bassel5:gsub('L','𝒍')
bassel5= bassel5:gsub('l','𝒍')
bassel5= bassel5:gsub('z','𝒛')
bassel5= bassel5:gsub('Z','𝒛')
bassel5= bassel5:gsub('x','𝒙')
bassel5= bassel5:gsub('X','𝒙')
bassel5= bassel5:gsub('c','𝒄')
bassel5= bassel5:gsub('C','𝒄')
bassel5= bassel5:gsub('v','𝒗')
bassel5= bassel5:gsub('V','𝒗')
bassel5= bassel5:gsub('b','𝒃')
bassel5= bassel5:gsub('B','𝒃')
bassel5= bassel5:gsub('n','𝒏')
bassel5= bassel5:gsub('N','𝒏')
bassel5= bassel5:gsub('m','𝒎')
bassel5= bassel5:gsub('M','𝒎')



local bassel6= Text:gsub('ض','ﺿ̭͠')
bassel6= bassel6:gsub('ص','ﺻ͡')
bassel6= bassel6:gsub('ث','ﺜ̲')
bassel6= bassel6:gsub('ق','ﭰ')
bassel6= bassel6:gsub('ف','ﻓ̲')
bassel6= bassel6:gsub('غ','ﻏ̲')
bassel6= bassel6:gsub('ع','ﻌ̲')
bassel6= bassel6:gsub('ه','ﮬ̲̌')
bassel6= bassel6:gsub('خ','خٌ')
bassel6= bassel6:gsub('ح','ﺣ̅')
bassel6= bassel6:gsub('ج','جُ')
bassel6= bassel6:gsub('د','ډ̝')
bassel6= bassel6:gsub('ذ','ذً')
bassel6= bassel6:gsub('ش','ﺷ̲')
bassel6= bassel6:gsub('س','ﺳ̉')
bassel6= bassel6:gsub('ي','ﯾ̃̐')
bassel6= bassel6:gsub('ب','ﺑ̲')
bassel6= bassel6:gsub('ل','ا̄ﻟ')
bassel6= bassel6:gsub('ا','ﺈ̃')
bassel6= bassel6:gsub('ت','ټُ')
bassel6= bassel6:gsub('ن','ﻧ̲')
bassel6= bassel6:gsub('م','ﻣ̲̉')
bassel6= bassel6:gsub('ك','گ')
bassel6= bassel6:gsub('ط','ﻁ̲')
bassel6= bassel6:gsub('ئ',' ْٰئ')
bassel6= bassel6:gsub('ء','ء')
bassel6= bassel6:gsub('ؤ','ؤ')
bassel6= bassel6:gsub('ر','ہڕ')
bassel6= bassel6:gsub('لا','ﻟ̲ﺂ̲')
bassel6= bassel6:gsub('ى','ى')
bassel6= bassel6:gsub('ة','ة')
bassel6= bassel6:gsub('و','ۇۈۉ')
bassel6= bassel6:gsub('ز','زُ')
bassel6= bassel6:gsub('ظ','ﻇ̲')
bassel6= bassel6:gsub('q','ǫ')
bassel6= bassel6:gsub('Q','ǫ')
bassel6= bassel6:gsub('w','ᴡ')
bassel6= bassel6:gsub('W','ᴡ')
bassel6= bassel6:gsub('e','ᴇ')
bassel6= bassel6:gsub('E','ᴇ')
bassel6= bassel6:gsub('r','ʀ')
bassel6= bassel6:gsub('R','ʀ')
bassel6= bassel6:gsub('t','ᴛ')
bassel6= bassel6:gsub('T','ᴛ')
bassel6= bassel6:gsub('y','ʏ')
bassel6= bassel6:gsub('Y','ʏ')
bassel6= bassel6:gsub('u','ụ')
bassel6= bassel6:gsub('U','ụ')
bassel6= bassel6:gsub('i','ɪ')
bassel6= bassel6:gsub('I','ɪ')
bassel6= bassel6:gsub('o','ᴏ')
bassel6= bassel6:gsub('O','ᴏ')
bassel6= bassel6:gsub('p','ᴘ')
bassel6= bassel6:gsub('P','ᴘ')
bassel6= bassel6:gsub('a','ᴀ')
bassel6= bassel6:gsub('A','ᴀ')
bassel6= bassel6:gsub('s','ѕ')
bassel6= bassel6:gsub('S','ѕ')
bassel6= bassel6:gsub('d','ᴅ')
bassel6= bassel6:gsub('D','ᴅ')
bassel6= bassel6:gsub('f','ғ')
bassel6= bassel6:gsub('F','ғ')
bassel6= bassel6:gsub('g','ɢ')
bassel6= bassel6:gsub('G','ɢ')
bassel6= bassel6:gsub('h','ʜ')
bassel6= bassel6:gsub('H','ʜ')
bassel6= bassel6:gsub('j','ᴊ')
bassel6= bassel6:gsub('J','ᴊ')
bassel6= bassel6:gsub('K','ᴋ')
bassel6= bassel6:gsub('k','ᴋ')
bassel6= bassel6:gsub('L','ʟ')
bassel6= bassel6:gsub('l','ʟ')
bassel6= bassel6:gsub('z','ᴢ')
bassel6= bassel6:gsub('Z','ᴢ')
bassel6= bassel6:gsub('x','х')
bassel6= bassel6:gsub('X','х')
bassel6= bassel6:gsub('c','ᴄ')
bassel6= bassel6:gsub('C','ᴄ')
bassel6= bassel6:gsub('v','ᴠ')
bassel6= bassel6:gsub('V','ᴠ')
bassel6= bassel6:gsub('b','ʙ')
bassel6= bassel6:gsub('B','ʙ')
bassel6= bassel6:gsub('n','ɴ')
bassel6= bassel6:gsub('N','ɴ')
bassel6= bassel6:gsub('m','ᴍ')
bassel6= bassel6:gsub('M','ᴍ')



local bassel7= Text:gsub('ض','ﺿ')
bassel7= bassel7:gsub('ص','ﺻ')
bassel7= bassel7:gsub('ث','ﭥ')
bassel7= bassel7:gsub('ق','ﻗ̮ـ̃')
bassel7= bassel7:gsub('ف','ﭬ')
bassel7= bassel7:gsub('غ','ﻏ̣̐')
bassel7= bassel7:gsub('ع','ﻋ')
bassel7= bassel7:gsub('ه','ھَہّ')
bassel7= bassel7:gsub('خ','ﺧ')
bassel7= bassel7:gsub('ح','פ')
bassel7= bassel7:gsub('ج','ﭴ')
bassel7= bassel7:gsub('د','ﮃ')
bassel7= bassel7:gsub('ذ','ذ')
bassel7= bassel7:gsub('ش','ﺷ')
bassel7= bassel7:gsub('س','ﺳ')
bassel7= bassel7:gsub('ي','ﯾ')
bassel7= bassel7:gsub('ب','ﺑ')
bassel7= bassel7:gsub('ل','ﻟ')
bassel7= bassel7:gsub('ا','ﺂ')
bassel7= bassel7:gsub('ت','ﭠ')
bassel7= bassel7:gsub('ن','ﻧ')
bassel7= bassel7:gsub('م','ﻣ̝̚')
bassel7= bassel7:gsub('ك','گـ')
bassel7= bassel7:gsub('ط','ﻁْ')
bassel7= bassel7:gsub('ئ','ٰئـ')
bassel7= bassel7:gsub('ء','ء')
bassel7= bassel7:gsub('ؤ','ﯗ')
bassel7= bassel7:gsub('ر','ړُ')
bassel7= bassel7:gsub('لا','ﻟآ')
bassel7= bassel7:gsub('ى','ـﮯ')
bassel7= bassel7:gsub('ة','ة')
bassel7= bassel7:gsub('و','ۆ')
bassel7= bassel7:gsub('ز','ژ')
bassel7= bassel7:gsub('ظ','ﻅ')
bassel7= bassel7:gsub('q','𝘘')
bassel7= bassel7:gsub('Q','𝘘')
bassel7= bassel7:gsub('w','𝘞')
bassel7= bassel7:gsub('W','𝘞')
bassel7= bassel7:gsub('e','𝘌')
bassel7= bassel7:gsub('E','𝘌')
bassel7= bassel7:gsub('r','𝘙')
bassel7= bassel7:gsub('R','𝘙')
bassel7= bassel7:gsub('t','𝘛')
bassel7= bassel7:gsub('T','𝘛')
bassel7= bassel7:gsub('y','𝘠')
bassel7= bassel7:gsub('Y','𝘠')
bassel7= bassel7:gsub('u','𝘜')
bassel7= bassel7:gsub('U','𝘜')
bassel7= bassel7:gsub('i','𝘐')
bassel7= bassel7:gsub('I','𝘐')
bassel7= bassel7:gsub('o','𝘖')
bassel7= bassel7:gsub('O','𝘖')
bassel7= bassel7:gsub('p','𝘗')
bassel7= bassel7:gsub('P','𝘗')
bassel7= bassel7:gsub('a','𝘈')
bassel7= bassel7:gsub('A','𝘈')
bassel7= bassel7:gsub('s','𝘚')
bassel7= bassel7:gsub('S','𝘚')
bassel7= bassel7:gsub('d','𝘋')
bassel7= bassel7:gsub('D','𝘋')
bassel7= bassel7:gsub('f','𝘍')
bassel7= bassel7:gsub('F','𝘍')
bassel7= bassel7:gsub('g','𝘎')
bassel7= bassel7:gsub('G','𝘎')
bassel7= bassel7:gsub('h','𝘏')
bassel7= bassel7:gsub('H','𝘏')
bassel7= bassel7:gsub('j','𝘑')
bassel7= bassel7:gsub('J','𝘑')
bassel7= bassel7:gsub('k','𝘒')
bassel7= bassel7:gsub('K','𝘒')
bassel7= bassel7:gsub('L','𝘓')
bassel7= bassel7:gsub('l','𝘓')
bassel7= bassel7:gsub('z','𝘡')
bassel7= bassel7:gsub('Z','𝘡')
bassel7= bassel7:gsub('x','𝘟')
bassel7= bassel7:gsub('X','𝘟')
bassel7= bassel7:gsub('c','𝘊')
bassel7= bassel7:gsub('C','𝘊')
bassel7= bassel7:gsub('v','𝘝')
bassel7= bassel7:gsub('V','𝘝')
bassel7= bassel7:gsub('b','𝘉')
bassel7= bassel7:gsub('B','𝘉')
bassel7= bassel7:gsub('n','𝘕')
bassel7= bassel7:gsub('N','𝘕')
bassel7= bassel7:gsub('m','𝘔')
bassel7= bassel7:gsub('M','𝘔')



local bassel8= Text:gsub('ض','ض');
bassel8= bassel8:gsub('ص','صہٰ')
bassel8= bassel8:gsub('ث','ثہٰـ')
bassel8= bassel8:gsub('ق','قہٰ')
bassel8= bassel8:gsub('ف','فہٰ')
bassel8= bassel8:gsub('غ','غـْ')
bassel8= bassel8:gsub('ع','ع')
bassel8= bassel8:gsub('ه','هٰہٰٖ')
bassel8= bassel8:gsub('خ','خخَـ')
bassel8= bassel8:gsub('ح','حہٰ')
bassel8= bassel8:gsub('ج','ججہٰ')
bassel8= bassel8:gsub('د','دَ')
bassel8= bassel8:gsub('ذ','ذّ')
bassel8= bassel8:gsub('ش','ششہٰ')
bassel8= bassel8:gsub('س','سہٰ')
bassel8= bassel8:gsub('ي','يٰ')
bassel8= bassel8:gsub('ب','بٰٰ')
bassel8= bassel8:gsub('ل','لہٰ')
bassel8= bassel8:gsub('ا','آ')
bassel8= bassel8:gsub('ت','تہٰ')
bassel8= bassel8:gsub('ن','نہٰ')
bassel8= bassel8:gsub('م','مہٰ')
bassel8= bassel8:gsub('ك','ككہٰ')
bassel8= bassel8:gsub('ط','طہٰ')
bassel8= bassel8:gsub('ئ',' ْئٰ')
bassel8= bassel8:gsub('ء','ء')
bassel8= bassel8:gsub('ؤ','ؤؤَ')
bassel8= bassel8:gsub('ر','رَ')
bassel8= bassel8:gsub('لا','لہٰا')
bassel8= bassel8:gsub('ى','ىہٰ')
bassel8= bassel8:gsub('ة','ة')
bassel8= bassel8:gsub('و','ہٰو')
bassel8= bassel8:gsub('ز','ز')
bassel8= bassel8:gsub('ظ','ظہٰ')
bassel8= bassel8:gsub('q','𝚀')
bassel8= bassel8:gsub('Q','𝚀')
bassel8= bassel8:gsub('w','𝚆')
bassel8= bassel8:gsub('W','𝚆')
bassel8= bassel8:gsub('e','𝙴')
bassel8= bassel8:gsub('E','𝙴')
bassel8= bassel8:gsub('r','𝚁')
bassel8= bassel8:gsub('R','𝚁')
bassel8= bassel8:gsub('t','𝚃')
bassel8= bassel8:gsub('T','𝚃')
bassel8= bassel8:gsub('y','𝚈')
bassel8= bassel8:gsub('Y','𝚈')
bassel8= bassel8:gsub('u','𝚄')
bassel8= bassel8:gsub('U','𝚄')
bassel8= bassel8:gsub('i','𝙸')
bassel8= bassel8:gsub('I','𝙸')
bassel8= bassel8:gsub('o','𝙾')
bassel8= bassel8:gsub('O','𝙾')
bassel8= bassel8:gsub('p','𝙿')
bassel8= bassel8:gsub('P','𝙿')
bassel8= bassel8:gsub('a','𝙰')
bassel8= bassel8:gsub('A','𝙰')
bassel8= bassel8:gsub('s','𝚂')
bassel8= bassel8:gsub('S','𝚂')
bassel8= bassel8:gsub('d','𝙳')
bassel8= bassel8:gsub('D','𝙳')
bassel8= bassel8:gsub('f','𝙵')
bassel8= bassel8:gsub('F','𝙵')
bassel8= bassel8:gsub('g','𝙶')
bassel8= bassel8:gsub('G','𝙶')
bassel8= bassel8:gsub('h','𝙷')
bassel8= bassel8:gsub('H','𝙷')
bassel8= bassel8:gsub('j','𝙹')
bassel8= bassel8:gsub('J','𝙹')
bassel8= bassel8:gsub('k','𝙺')
bassel8= bassel8:gsub('K','𝙺')
bassel8= bassel8:gsub('L','𝙻')
bassel8= bassel8:gsub('l','𝙻')
bassel8= bassel8:gsub('z','𝚉')
bassel8= bassel8:gsub('Z','𝚉')
bassel8= bassel8:gsub('x','𝚇')
bassel8= bassel8:gsub('X','𝚇')
bassel8= bassel8:gsub('c','𝙲')
bassel8= bassel8:gsub('C','𝙲')
bassel8= bassel8:gsub('v','𝚅')
bassel8= bassel8:gsub('V','𝚅')
bassel8= bassel8:gsub('b','𝙱')
bassel8= bassel8:gsub('B','𝙱')
bassel8= bassel8:gsub('n','𝙽')
bassel8= bassel8:gsub('N','𝙽')
bassel8= bassel8:gsub('m','𝙼')
bassel8= bassel8:gsub('M','𝙼')



local bassel9= Text:gsub('ض','ض')
bassel9= bassel9:gsub('ص','ص')
bassel9= bassel9:gsub('ث','ث')
bassel9= bassel9:gsub('ق','قٌ')
bassel9= bassel9:gsub('ف','فُ')
bassel9= bassel9:gsub('غ','غ')
bassel9= bassel9:gsub('ع','عٍ')
bassel9= bassel9:gsub('ه','هـ')
bassel9= bassel9:gsub('خ','خـ')
bassel9= bassel9:gsub('ح','حٍ')
bassel9= bassel9:gsub('ج','جٍ')
bassel9= bassel9:gsub('د','دِ')
bassel9= bassel9:gsub('ذ','ذَ')
bassel9= bassel9:gsub('ش','شُ')
bassel9= bassel9:gsub('س','س')
bassel9= bassel9:gsub('ي','ي')
bassel9= bassel9:gsub('ب','بَ')
bassel9= bassel9:gsub('ل','لُِ')
bassel9= bassel9:gsub('ا','آ')
bassel9= bassel9:gsub('ت','ت')
bassel9= bassel9:gsub('ن','ن')
bassel9= bassel9:gsub('م','م')
bassel9= bassel9:gsub('ك','ڪ')
bassel9= bassel9:gsub('ط','طُ')
bassel9= bassel9:gsub('ئ','ئ ْٰ')
bassel9= bassel9:gsub('ء','ء')
bassel9= bassel9:gsub('ؤ','ؤ')
bassel9= bassel9:gsub('ر','ر')
bassel9= bassel9:gsub('لا','لُِآ')
bassel9= bassel9:gsub('ى','ىْ')
bassel9= bassel9:gsub('ة','ة')
bassel9= bassel9:gsub('و','وو')
bassel9= bassel9:gsub('ز','ز')
bassel9= bassel9:gsub('ظ','ظهُ')
bassel9= bassel9:gsub('q','ℚ')
bassel9= bassel9:gsub('Q','ℚ')
bassel9= bassel9:gsub('w','𝕎')
bassel9= bassel9:gsub('W','𝕎')
bassel9= bassel9:gsub('e','𝔼')
bassel9= bassel9:gsub('E','𝔼')
bassel9= bassel9:gsub('r','ℝ')
bassel9= bassel9:gsub('R','ℝ')
bassel9= bassel9:gsub('t','𝕋')
bassel9= bassel9:gsub('T','𝕋')
bassel9= bassel9:gsub('y','𝕐')
bassel9= bassel9:gsub('Y','𝕐')
bassel9= bassel9:gsub('u','𝕌')
bassel9= bassel9:gsub('U','𝕌')
bassel9= bassel9:gsub('i','𝕀')
bassel9= bassel9:gsub('I','𝕀')
bassel9= bassel9:gsub('o','𝕆')
bassel9= bassel9:gsub('O','𝕆')
bassel9= bassel9:gsub('p','ℙ')
bassel9= bassel9:gsub('P','ℙ')
bassel9= bassel9:gsub('a','𝔸')
bassel9= bassel9:gsub('A','𝔸')
bassel9= bassel9:gsub('s','𝕊')
bassel9= bassel9:gsub('S','𝕊')
bassel9= bassel9:gsub('d','𝔻')
bassel9= bassel9:gsub('D','𝔻')
bassel9= bassel9:gsub('f','𝔽')
bassel9= bassel9:gsub('F','𝔽')
bassel9= bassel9:gsub('g','𝔾')
bassel9= bassel9:gsub('G','𝔾')
bassel9= bassel9:gsub('h','ℍ')
bassel9= bassel9:gsub('H','ℍ')
bassel9= bassel9:gsub('j','𝕁')
bassel9= bassel9:gsub('J','𝕁')
bassel9= bassel9:gsub('k','𝕂')
bassel9= bassel9:gsub('K','𝕂')
bassel9= bassel9:gsub('L','𝕃')
bassel9= bassel9:gsub('l','𝕃')
bassel9= bassel9:gsub('z','ℤ')
bassel9= bassel9:gsub('Z','ℤ')
bassel9= bassel9:gsub('x','𝕏')
bassel9= bassel9:gsub('X','𝕏')
bassel9= bassel9:gsub('c','ℂ')
bassel9= bassel9:gsub('C','ℂ')
bassel9= bassel9:gsub('v','𝕍')
bassel9= bassel9:gsub('V','𝕍')
bassel9= bassel9:gsub('b','𝔹')
bassel9= bassel9:gsub('B','𝔹')
bassel9= bassel9:gsub('n','ℕ')
bassel9= bassel9:gsub('N','ℕ')
bassel9= bassel9:gsub('m','𝕄')
bassel9= bassel9:gsub('M','𝕄')


local Text_bassela = "1- `"..bassel..EmojeS[math.random(#EmojeS)]
.."`\n\n2- `"..bassel2..EmojeS[math.random(#EmojeS)]
.."`\n\n3- `"..bassel3..EmojeS[math.random(#EmojeS)]
.."`\n\n4- `"..bassel4..EmojeS[math.random(#EmojeS)]
.."`\n\n5- `"..bassel5..EmojeS[math.random(#EmojeS)]
.."`\n\n6- `"..bassel6..EmojeS[math.random(#EmojeS)]
.."`\n\n7- `"..bassel7..EmojeS[math.random(#EmojeS)]
.."`\n\n8- `"..bassel8..Emoje[math.random(#Emoje)]
.."`\n\n9- `"..bassel9..Emoje[math.random(#Emoje)]
.."`\n\n10- `"..bassel5..Emoje[math.random(#Emoje)]
Text_bassela = Text_bassela.."`\n\n| اضغـط علـي الاسـم ليتـم النـسخ  \n★"
sendMsg(msg.chat_id_,msg.id_,Text_bassela)
return false
end



end

return {
black = {
"^(زخرفه)$"
 },
 iblack = bassela,
 dblack = TextRes,
 }
 
 

--[[
███████▀ │black ﹏  @V_P_E
│تم تطوير وبرمجة السورس من قبل جاك ✺
│@ BLACK_TEAM_3
#-------------------------------------------------------------------
]]
